//
///////////////////////////////////////////////////////////////////////////////////////////
// Copyright © 2010-2013, Xilinx, Inc.
// This file contains confidential and proprietary information of Xilinx, Inc. and is
// protected under U.S. and international copyright and other intellectual property laws.
///////////////////////////////////////////////////////////////////////////////////////////
//
// Disclaimer:
// This disclaimer is not a license and does not grant any rights to the materials
// distributed herewith. Except as otherwise provided in a valid license issued to
// you by Xilinx, and to the maximum extent permitted by applicable law: (1) THESE
// MATERIALS ARE MADE AVAILABLE "AS IS" AND WITH ALL FAULTS, AND XILINX HEREBY
// DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY,
// INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT,
// OR FITNESS FOR ANY PARTICULAR PURPOSE; and (2) Xilinx shall not be liable
// (whether in contract or tort, including negligence, or under any other theory
// of liability) for any loss or damage of any kind or nature related to, arising
// under or in connection with these materials, including for any direct, or any
// indirect, special, incidental, or consequential loss or damage (including loss
// of data, profits, goodwill, or any type of loss or damage suffered as a result
// of any action brought by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the possibility of the same.
//
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-safe, or for use in any
// application requiring fail-safe performance, such as life-support or safety
// devices or systems, Class III medical devices, nuclear facilities, applications
// related to the deployment of airbags, or any other applications that could lead
// to death, personal injury, or severe property or environmental damage
// (individually and collectively, "Critical Applications"). Customer assumes the
// sole risk and liability of any use of Xilinx products in Critical Applications,
// subject only to applicable laws and regulations governing limitations on product
// liability.
//
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE AT ALL TIMES.
//
///////////////////////////////////////////////////////////////////////////////////////////
//
//
// Production definition of a 1K program for KCPSM6 in a 7-Series device using a 
// RAMB18E1 primitive.
//
// Note: The complete 12-bit address bus is connected to KCPSM6 to facilitate future code 
//       expansion with minimum changes being required to the hardware description. 
//       Only the lower 10-bits of the address are actually used for the 1K address range
//       000 to 3FF hex.  
//
// Program defined by 'Z:\home\daniel\Documents\tareas\maestria\pdae\hardware_reconfig\proyecto\codigo\prime_adder.psm'.
//
// Generated by KCPSM6 Assembler: 25 Oct 2025 - 18:18:23. 
//
// Assembler used ROM_form template: ROM_form_7S_1K_14March13.v
//
//
module prime_adder (
input  [11:0] address,
output [17:0] instruction,
input         enable,
input         clk);
//
//
wire [13:0] address_a;
wire [17:0] data_in_a;
wire [17:0] data_out_a;
wire [13:0] address_b;
wire [17:0] data_in_b;
wire [17:0] data_out_b;
wire        enable_b;
wire        clk_b;
wire [3:0]  we_b;
//
//
assign address_a = {address[9:0], 4'b1111};
assign instruction = data_out_a[17:0];
assign data_in_a = {16'h0000, address[11:10]};
//
assign address_b = 14'b11111111111111;
assign data_in_b = data_out_b[17:0];
assign enable_b = 1'b0;
assign we_b = 4'h0;
assign clk_b = 1'b0;
//
// 
RAMB18E1 # ( .READ_WIDTH_A              (18),
             .WRITE_WIDTH_A             (18),
             .DOA_REG                   (0),
             .INIT_A                    (16'b000000000000000000),
             .RSTREG_PRIORITY_A         ("REGCE"),
             .SRVAL_A                   (36'h000000000000000000),
             .WRITE_MODE_A              ("WRITE_FIRST"),
             .READ_WIDTH_B              (18),
             .WRITE_WIDTH_B             (18),
             .DOB_REG                   (0),
             .INIT_B                    (36'h000000000000000000),
             .RSTREG_PRIORITY_B         ("REGCE"),
             .SRVAL_B                   (36'h000000000000000000),
             .WRITE_MODE_B              ("WRITE_FIRST"),
             .INIT_FILE                 ("NONE"),
             .SIM_COLLISION_CHECK       ("ALL"),
             .RAM_MODE                  ("TDP"),
             .RDADDR_COLLISION_HWCONFIG ("DELAYED_WRITE"),
             .SIM_DEVICE                ("7SERIES"),
             .INIT_00                   (256'hD106D00594FF1600940193FF1600930018001700160015001400130010001100),
             .INIT_01                   (256'hD27F2026D700370107202023D20292FF160092021600D603054005300630D804),
             .INIT_02                   (256'hD203202AD804D106D005180120141601202AC650202631000020E06AA02F2023),
             .INIT_03                   (256'hD21D2023D2172023D2132023D2112023D20D2023D20B2023D2072023D2052023),
             .INIT_04                   (256'hD23D2023D23B2023D2352023D22F2023D22B2023D2292023D2252023D21F2023),
             .INIT_05                   (256'hD2652023D2612023D2592023D2532023D24F2023D2492023D2472023D2432023),
             .INIT_06                   (256'h2023D28B2023D2892023D28320262023D2712023D26D2023D26B2023D2672023),
             .INIT_07                   (256'h2023D2B52023D2B32023D2AD2023D2A72023D2A32023D29D2023D2972023D295),
             .INIT_08                   (256'h2023D2E52023D2E32023D2DF2023D2D32023D2C72023D2C52023D2C12023D2BF),
             .INIT_09                   (256'h000000000000000000000000000020262023D2FB2023D2F12023D2EF2023D2E9),
             .INIT_0A                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_0B                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_0C                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_0D                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_0E                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_0F                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_10                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_11                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_12                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_13                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_14                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_15                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_16                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_17                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_18                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_19                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_1A                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_1B                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_1C                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_1D                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_1E                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_1F                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_20                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_21                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_22                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_23                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_24                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_25                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_26                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_27                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_28                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_29                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2A                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2B                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2C                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2D                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2E                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_2F                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_30                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_31                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_32                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_33                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_34                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_35                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_36                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_37                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_38                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_39                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3A                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3B                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3C                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3D                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3E                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INIT_3F                   (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_00                  (256'hDDDDDDDDDDDB77777777777777777777777777776A89D97F74344642A1040000),
             .INITP_01                  (256'h0000000000000000000000000000000000000000000000000002DDDDDDDDDDDD),
             .INITP_02                  (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_03                  (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_04                  (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_05                  (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_06                  (256'h0000000000000000000000000000000000000000000000000000000000000000),
             .INITP_07                  (256'h0000000000000000000000000000000000000000000000000000000000000000))
 kcpsm6_rom( .ADDRARDADDR               (address_a),
             .ENARDEN                   (enable),
             .CLKARDCLK                 (clk),
             .DOADO                     (data_out_a[15:0]),
             .DOPADOP                   (data_out_a[17:16]), 
             .DIADI                     (data_in_a[15:0]),
             .DIPADIP                   (data_in_a[17:16]), 
             .WEA                       (2'b00),
             .REGCEAREGCE               (1'b0),
             .RSTRAMARSTRAM             (1'b0),
             .RSTREGARSTREG             (1'b0),
             .ADDRBWRADDR               (address_b),
             .ENBWREN                   (enable_b),
             .CLKBWRCLK                 (clk_b),
             .DOBDO                     (data_out_b[15:0]),
             .DOPBDOP                   (data_out_b[17:16]), 
             .DIBDI                     (data_in_b[15:0]),
             .DIPBDIP                   (data_in_b[17:16]), 
             .WEBWE                     (we_b),
             .REGCEB                    (1'b0),
             .RSTRAMB                   (1'b0),
             .RSTREGB                   (1'b0));
//
//
endmodule
//
////////////////////////////////////////////////////////////////////////////////////
//
// END OF FILE prime_adder.v
//
////////////////////////////////////////////////////////////////////////////////////
